slam_toolbox:
  ros__parameters:
    use_sim_time: true

    # frames (à adapter à TON TF)
    map_frame: map
    odom_frame: odom
    base_frame: robot_center   # 

    # Topics
    scan_topic: scan
    throttle_scans: 1

    # timings
    transform_publish_period: 0.05
    map_update_interval: 2.0
    map_publish_period: 1.0

    # divers (optionnel)
    minimum_time_interval: 0.0
    tf_buffer_duration: 30.0

    # Robustesse TF / scan
    transform_timeout: 0.5
    scan_queue_size: 200
  
    # Bon compromis mapping temps réel
    mode: mapping




